
logging:
  level:
    com.sihookang.triple_submission: error
    com.sihookang.triple_submission.applictions: INFO
  pattern:
    console: '%d{yyyy-MM-DD HH:MM:ss.SSS} [%thread] %-5level [%C::%M %L] %logger{15} - %msg%n'
  


spring:
  datasource:
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    hikari:
      schema: classpath*:/schema/*.sql
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
    show-sql: true
